services:
  database:
    image: mysql:${MYSQL_VERSION:-8.0}-oracle
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-db}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-user}
    command: ["--log_bin_trust_function_creators=1"]
    volumes:
      - db-data:/var/lib/mysql:rw

  mailer:
    image: axllent/mailpit
    ports:
      - '8025:8025'
      - '1025:1025'

volumes:
  db-data:
